### ISSUE TITLE
Baked Lut Notice

### ISSUE THREAD

**Issue by melMass** [colour-science/OpenColorIO-Configs#15]
Hi,
![image](https://user-images.githubusercontent.com/7041726/142876336-7cc6da3b-f69e-48da-afa0-57ce32650041.png)

Can you briefly explain what the baked luts are used for?
I'm mainly using Houdini Nuke and Davinci and aces 1.2

Thanks

**Comment by KelSolaar** [comment]
Hi @melMass,

The following directory is removed basically: https://github.com/colour-science/OpenColorIO-Configs/tree/master/aces_1.2/baked

Cheers,

Thomas

**Comment by melMass** [comment]
Thanks Thomas, I meant what are those baked lut used for? 
Is it only a matter of processing time or does it serve a specific purpose

**Comment by KelSolaar** [comment]
They can be used with software that does not support OCIO natively, in your case, I think you should be covered and can use the smaller zip file!

Cheers,

Thomas

**Comment by melMass** [comment]
Thanks for the clarification 🙏
