### ISSUE TITLE
Cannot download the source file of 1.2 config zip

### ISSUE THREAD

**Issue by vyshnavks8** [colour-science/OpenColorIO-Configs#5]
Every time downloading the source of widows zip of 1.2 config it stops after 1.02gb I tried 4,5 times. Please resolve this issue

**Comment by KelSolaar** [comment]
Hi @vyshnavks8,

Nothing I can do about that, this is a Github issue. Cloning the repository should work.

Cheers,

**Comment by vyshnavks8** [comment]
Thanks
