### ISSUE TITLE
aces_1.2 folder is corrupt

### ISSUE THREAD

**Issue by sanketvaria** [colour-science/OpenColorIO-Configs#6]
I downloaded the zip file from many different browsers but all of them says that aces_1.2 folder is corrupted and hence can't be extracted. i tried winrar, 7zip and power archiver, none of them worked. aces_1.1 folder is corrupted as well in the previous branch. My download stops at 1.01 GB and then fails to download further.

**Comment by KelSolaar** [comment]
Hi,

You cannot really download directly from Github, it is too big. You either need to clone the repo or try the lean 124mb version from the releases page: https://github.com/colour-science/OpenColorIO-Configs/releases/tag/v1.2

Cheers,

Thomas
